apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: 35.224.37.7.nip.io
    http:
      paths:
      - path: /users(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-users
            port:
              number: 8000
      - path: /products(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-products
            port:
              number: 8000
      - path: /financial(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-financial
            port:
              number: 8000
      - path: /orders(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-order
            port:
              number: 8000
