apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-users-db
spec:
  selector:
    app: {{ .Release.Name }}-users-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-users
spec:
  selector:
    app: {{ .Release.Name }}-users
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-users
  labels:
    app: {{ .Release.Name }}-users
spec:
  replicas: {{ .Values.users.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-users
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-users
    spec:
      containers:
        - name: app
          image: {{ .Values.users.image }}:{{ .Values.users.tag }}
          ports:
          - containerPort: 8000
            protocol: TCP
          command: 
            - python
          args:
            - manage.py
            - runserver 
            - 0.0.0.0:8000
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: DB_NAME
              value: "users"
            - name: DB_USER
              value: "users"
            - name: DB_PASS
              value: "123"
            - name: "FINANCIAL_ROOT_URL"
              value: "{{ .Release.Name }}-financial.{{ .Release.Namespace }}.svc.cluster.local:8000"
            - name: "DB_HOST"
              value: "{{ .Release.Name }}-users-db-0.{{ .Release.Name }}-users-db.{{ .Release.Namespace }}.svc.cluster.local"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-users-db
  labels:
    app: {{ .Release.Name }}-users-db
spec:
  serviceName: {{ .Release.Name }}-users-db
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-users-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-users-db
    spec:
      containers:
        - name: db
          image: {{ .Values.postgres.image }}:{{ .Values.postgres.tag }}
          ports:
          - containerPort: 5432
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: POSTGRES_DB
              value: "users"
            - name: POSTGRES_USER
              value: "users"
            - name: POSTGRES_PASSWORD
              value: "123"
            - name: "PGDATA"
              value: /var/lib/postgresql/data/db
          volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data/

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard-rwo"
      resources:
        requests:
          storage: 1Gi